import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFDF1',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(86, 47, 0, 0.5)',
    zIndex: 999,
  },
  sidebarContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 280,
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  mainContent: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF9644',
    paddingVertical: 20,
    paddingHorizontal: 20,
    paddingTop: 48,
    shadowColor: '#562F00',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 8,
  },
  menuButton: {
    padding: 10,
    marginRight: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 12,
  },
  hamburgerContainer: {
    width: 24,
    height: 18,
    justifyContent: 'space-between',
  },
  hamburgerLine: {
    width: 24,
    height: 3,
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
  },
  headerContent: {
    flex: 1,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerLogo: {
    width: 50,
    height: 50,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'Oswald_700Bold',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  headerSubtitle: {
    fontSize: 15,
    fontFamily: 'NunitoSans_400Regular',
    color: '#FFFFFF',
    opacity: 0.85,
    marginTop: 4,
  },
  scrollContent: {
    paddingBottom: 40,
    paddingTop: 16,
  },
  sectionContainer: {
      marginBottom: 5,
  },
  sectionHeader: {
    paddingHorizontal: 20,
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'Oswald_700Bold',
    color: '#562F00',
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  sectionSubtitle: {
    fontSize: 13,
    fontFamily: 'NunitoSans_400Regular',
    color: '#8B5A1A',
    fontWeight: '400',
  },
  horizontalScroll: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingVertical: 10,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingHorizontal: 20,
    gap: 24,
    flexWrap: 'wrap',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    fontFamily: 'Oswald_700Bold',
    color: '#FF6B6B',
    marginBottom: 8,
  },
  description: {
    fontSize: 16,
    fontFamily: 'NunitoSans_400Regular',
    color: '#666666',
    marginBottom: 24,
    lineHeight: 24,
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    borderLeftWidth: 4,
    borderLeftColor: '#FF6B6B',
  },
  successCard: {
    borderLeftColor: '#4ECDC4',
    backgroundColor: '#F0FFFE',
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Oswald_600SemiBold',
    color: '#333333',
    marginBottom: 12,
  },
  successTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'Oswald_700Bold',
    color: '#4ECDC4',
    marginBottom: 12,
  },
  infoText: {
    fontSize: 15,
    fontFamily: 'NunitoSans_400Regular',
    color: '#666666',
    marginBottom: 8,
    lineHeight: 24,
  },
  successText: {
    fontSize: 15,
    fontFamily: 'NunitoSans_400Regular',
    color: '#2D6A63',
    lineHeight: 24,
  },
  tipText: {
    fontSize: 14,
    fontFamily: 'NunitoSans_400Regular',
    color: '#FF6B6B',
    marginTop: 8,
    fontStyle: 'italic',
  },
  boldText: {
    fontWeight: 'bold',
    color: '#FF6B6B',
    textTransform: 'capitalize',
  },
});
