import { StyleSheet } from 'react-native';
import { Colors } from './theme';

export const recipesScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFDF1',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF9644',
    paddingVertical: 14,
    paddingHorizontal: 20,
    paddingTop: 50,
    shadowColor: '#562F00',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  menuButton: {
    padding: 10,
    marginRight: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 12,
  },
  hamburgerContainer: {
    width: 24,
    height: 18,
    justifyContent: 'space-between',
  },
  hamburgerLine: {
    width: 24,
    height: 3,
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
  },
  backButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 10,
    marginRight: 14,
  },
  backButtonText: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '700',
    fontFamily: 'Oswald_600SemiBold',
    letterSpacing: 0.5,
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    fontFamily: 'Oswald_700Bold',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  headerSubtitle: {
    fontSize: 15,
    fontFamily: 'NunitoSans_400Regular',
    color: '#FFFFFF',
    opacity: 0.9,
    marginTop: 2,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 16,
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#FFD6A5',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  searchIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: 'NunitoSans_400Regular',
    color: '#562F00',
    padding: 10,
    paddingLeft: 0,
  },
  clearButton: {
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFE6CC',
    borderRadius: 14,
    marginLeft: 8,
  },
  clearButtonText: {
    fontSize: 16,
    color: '#8B5A1A',
    fontWeight: '700',
  },
  // Filter Button (replaces category chips)
  filterButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginBottom: 24,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#FFD6A5',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  filterButtonText: {
    fontSize: 16,
    fontFamily: 'NunitoSans_600SemiBold',
    color: '#562F00',
    fontWeight: '600',
  },
  filterButtonIcon: {
    fontSize: 12,
    color: '#8B5A1A',
    marginLeft: 8,
  },
  // Filter Modal
  filterModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  filterModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  filterModalTitle: {
    fontSize: 22,
    fontFamily: 'Oswald_700Bold',
    fontWeight: '700',
    color: '#562F00',
    marginBottom: 20,
    textAlign: 'center',
  },
  filterOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: '#FFF9F0',
  },
  filterOptionActive: {
    backgroundColor: Colors.primary,
  },
  filterOptionText: {
    fontSize: 16,
    fontFamily: 'NunitoSans_600SemiBold',
    fontWeight: '600',
    color: '#562F00',
  },
  filterOptionTextActive: {
    color: '#FFFFFF',
  },
  filterCheckmark: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  recipeGrid: {
    paddingHorizontal: 16,
    paddingBottom: 30,
    paddingTop: 4,
  },
  recipeRow: {
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 16,
  },
  recipeCardWrapper: {
    flex: 1,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyIcon: {
    fontSize: 64,
    marginBottom: 16,
  },
  emptyText: {
    fontSize: 20,
    fontFamily: 'Oswald_600SemiBold',
    fontWeight: '600',
    color: '#562F00',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 14,
    fontFamily: 'NunitoSans_400Regular',
    color: '#8B5A1A',
    textAlign: 'center',
  },
});
