import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from './theme';

const { width, height } = Dimensions.get('window');

export const recipeDetailModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    height: height * 0.9,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    backgroundColor: '#FFF',
  },
  headerTitle: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 20,
    fontWeight: '600',
    color: Colors.primary,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 20,
    color: Colors.textDark,
    fontWeight: '600',
  },
  scrollContent: {
    paddingBottom: 32,
  },
  recipeImage: {
    width: width,
    height: 250,
    backgroundColor: '#F5F5F5',
  },
  infoContainer: {
    padding: 20,
    backgroundColor: '#FFF',
  },
  recipeTitle: {
    fontFamily: 'Oswald_700Bold',
    fontSize: 28,
    fontWeight: '700',
    color: Colors.textDark,
    marginBottom: 8,
  },
  recipeSubtitle: {
    fontFamily: 'NunitoSans_400Regular',
    fontSize: 16,
    color: Colors.textMedium,
    marginBottom: 12,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ratingText: {
    fontFamily: 'NunitoSans_600SemiBold',
    fontSize: 16,
    fontWeight: '600',
    color: Colors.textDark,
  },
  reviewsText: {
    fontFamily: 'NunitoSans_400Regular',
    fontSize: 14,
    color: Colors.textMedium,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 20,
    paddingHorizontal: 20,
    backgroundColor: '#FFFAF5',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#FFE6CC',
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
  },
  statIcon: {
    fontSize: 28,
    marginBottom: 8,
  },
  statLabel: {
    fontFamily: 'NunitoSans_400Regular',
    fontSize: 12,
    color: Colors.textMedium,
    marginBottom: 4,
  },
  statValue: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 16,
    fontWeight: '600',
    color: Colors.textDark,
  },
  section: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  sectionTitle: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 20,
    fontWeight: '600',
    color: Colors.textDark,
    marginBottom: 16,
  },
  description: {
    fontFamily: 'NunitoSans_400Regular',
    fontSize: 15,
    lineHeight: 24,
    color: Colors.textMedium,
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 12,
    paddingRight: 20,
  },
  bullet: {
    fontFamily: 'NunitoSans_700Bold',
    fontSize: 18,
    color: Colors.primary,
    marginRight: 12,
    lineHeight: 24,
  },
  listText: {
    fontFamily: 'NunitoSans_400Regular',
    fontSize: 15,
    lineHeight: 24,
    color: Colors.textMedium,
    flex: 1,
  },
  instructionItem: {
    flexDirection: 'row',
    marginBottom: 20,
    paddingRight: 20,
  },
  stepNumber: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  stepNumberText: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 14,
    fontWeight: '600',
    color: '#FFF',
  },
  instructionText: {
    fontFamily: 'NunitoSans_400Regular',
    fontSize: 15,
    lineHeight: 24,
    color: Colors.textMedium,
    flex: 1,
    paddingTop: 4,
  },
  actionButtons: {
    padding: 20,
    gap: 12,
  },
  favoriteButton: {
    backgroundColor: '#FFF',
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  favoriteButtonText: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 16,
    fontWeight: '600',
    color: Colors.primary,
  },
  startButton: {
    backgroundColor: Colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  startButtonText: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 16,
    fontWeight: '600',
    color: '#FFF',
  },
});
